### ISSUE TITLE
Missing license. :)

### ISSUE THREAD

**Issue by JohnyWS** [niekcandaele/Catalysm-CSGO-config#1]
I'm starting [my own repo](https://github.com/JohnyWS/cs-go-config), with a lot of inspiration from your repo, and I was wondering, if there's any chance you could decide on a license for your repo? :)

I will be mentioning yours for sure, but mostly I [try to use Unlicense](https://unlicense.org/), but if that does not fit you, I'll be deleting my repo immediately and adjust it to whatever you decide here. :)

**Comment by niekcandaele** [comment]
Heya

Sorry for the late reply, missed the notification. Thanks for asking, I've added Unlicense to this repo, do whatever you want with it :smiley:
